
export const reservoirs = [
  {
    id: 0,
    label: 'Select...',
    value: '',
    disabled: true,

    name: '',
    max_volume: '',
    well_count: "",
    well_shape: '',
    rows: 0,
    cols: 0,
  },
  {
    id: 1,
    label: 'Agilent 1 Well Reservoir 290 ml',
    value: 'Agilent 1 Well Reservoir 290 ml',

    name: 'Agilent 1 Well Reservoir 290 ml',
    max_volume: '290 ml',
    well_count: 1,
    well_shape: 'V-bottom',
    rows: 1,
    cols: 1,
  },
  {
    id: 2,
    label: 'Axygen 1 Well Reservoir 90 ml',
    value: 'Axygen 1 Well Reservoir 90 ml',

    name: 'Axygen 1 Well Reservoir 90 ml',
    max_volume: '90 ml',
    well_count: 1,
    well_shape: 'Flat-bottom',
    rows: 1,
    cols: 1,

  },
  {
    id: 3,
    label: 'NEST 12 Well Reservoir 15 ml',
    value: 'NEST 12 Well Reservoir 15 ml',

    name: 'NEST 12 Well Reservoir 15 ml',
    max_volume: '15 ml',
    well_count: 12,
    well_shape: 'V-bottom',
    rows: 1,
    cols: 12,

  },
  {
    id: 3,
    label: 'NEST 1 Well Reservoir 195 ml',
    value: 'NEST 1 Well Reservoir 195 ml',

    name: 'NEST 1 Well Reservoir 195 ml',
    max_volume: '195 ml',
    well_count: 1,
    well_shape: 'V-bottom',
    rows: 1,
    cols: 1,
  },
  {
    id: 4,
    label: 'USA Scientific 12 Well Reservoir 22 mL',
    value: 'USA Scientific 12 Well Reservoir 22 mL',

    name: 'USA Scientific 12 Well Reservoir 22 mL',
    max_volume: '22 ml',
    well_count: 12,
    well_shape: 'V-bottom',
    rows: 1,
    cols: 12,
  },
]

export const well_plates = [
  {
    id: 0,
    label: 'Select...',
    value: '',
    disabled: true,
    squared: false,

    name: '',
    max_volume: '',
    well_count: 0,
    well_shape: '',
    rows: 0,
    cols: 0,
  },
  {
    id: 1,
    label: 'Applied Biosystems MicroAmp 384 Well Plate 40 µL',
    value: 'Applied Biosystems MicroAmp 384 Well Plate 40 µL',
    squared: false,

    name: 'Applied Biosystems MicroAmp 384 Well Plate 40 µL',
    max_volume: '40 μl',
    well_count: 384,
    well_shape: 'V-bottom',
    rows: 16,
    cols: 24,
  },
  {
    id: 2,
    label: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    value: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    squared: false,

    name: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    max_volume: '200 μl',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 3,
    label: 'Bio-Rad 384 Well Plate 50 µL',
    value: 'Bio-Rad 384 Well Plate 50 µL',
    squared: false,

    name: 'Bio-Rad 384 Well Plate 50 µL',
    max_volume: '50 μl',
    well_count: 384,
    well_shape: 'V-bottom',
    rows: 16,
    cols: 24,
  },
  {
    id: 4,
    label: 'Bio-Rad 96 Well Plate 200 µL PCR',
    value: 'Bio-Rad 96 Well Plate 200 µL PCR',
    squared: false,

    name: 'Bio-Rad 96 Well Plate 200 µL PCR',
    max_volume: '200 μl',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 5,
    label: 'Corning 12 Well Plate 6.9 mL Flat',
    value: 'Corning 12 Well Plate 6.9 mL Flat',
    squared: false,

    name: 'Corning 12 Well Plate 6.9 mL Flat',
    max_volume: '6.9 mL',
    well_count: 12,
    well_shape: 'Flat-bottom',
    rows: 3,
    cols: 4,
  },
  {
    id: 6,
    label: 'Corning 24 Well Plate 3.4 mL Flat',
    value: 'Corning 24 Well Plate 3.4 mL Flat',
    squared: false,

    name: 'Corning 24 Well Plate 3.4 mL Flat',
    max_volume: '3.4 mL',
    well_count: 24,
    well_shape: 'Flat-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 7,
    label: 'Corning 384 Well Plate 112 µL Flat',
    value: 'Corning 384 Well Plate 112 µL Flat',
    squared: true,

    name: 'Corning 384 Well Plate 112 µL Flat',
    max_volume: '112 μL',
    well_count: 384,
    well_shape: 'Flat-bottom',
    rows: 16,
    cols: 24,

  },
  {
    id: 8,
    label: 'Corning 48 Well Plate 1.6 mL Flat',
    value: 'Corning 48 Well Plate 1.6 mL Flat',
    squared: false,

    name: 'Corning 48 Well Plate 1.6 mL Flat',
    max_volume: '1.6 mL',
    well_count: 48,
    well_shape: 'Flat-bottom',
    rows: 6,
    cols: 8,

  },
  {
    id: 9,
    label: 'Corning 6 Well Plate 16.8 mL Flat',
    value: 'Corning 6 Well Plate 16.8 mL Flat',
    squared: false,

    name: 'Corning 6 Well Plate 16.8 mL Flat',
    max_volume: '16.8 mL',
    well_count: 6,
    well_shape: 'Flat-bottom',
    rows: 2,
    cols: 3,
  },
  {
    id: 10,
    label: 'Corning 96 Well Plate 360 µL Flat',
    value: 'Corning 96 Well Plate 360 µL Flat',
    squared: false,

    name: 'Corning 96 Well Plate 360 µL Flat',
    max_volume: '360 μL',
    well_count: 96,
    well_shape: 'Flat-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 11,
    label: 'NEST 96 Well Plate 100 µL PCR Full Skirt',
    value: 'NEST 96 Well Plate 100 µL PCR Full Skirt',
    squared: false,

    name: 'NEST 96 Well Plate 100 µL PCR Full Skirt',
    max_volume: '100 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 12,
    label: 'NEST 96 Well Plate 200 µL Flat',
    value: 'NEST 96 Well Plate 200 µL Flat',
    squared: false,

    name: 'NEST 96 Well Plate 200 µL Flat',
    max_volume: '200 μL',
    well_count: 96,
    well_shape: 'Flat-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 13,
    label: 'NEST 96 Deep Well Plate 2mL',
    value: 'NEST 96 Deep Well Plate 2mL',
    squared: false,

    name: 'NEST 96 Deep Well Plate 2mL',
    max_volume: '2 mL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 14,
    label: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    value: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    squared: false,

    name: 'Armadillo 96 Well Plate 200 µL PCR Full Skirt',
    max_volume: '2 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 15,
    label: 'Thermo Scientific Nunc 96 Well Plate 2000 µL',
    value: 'Thermo Scientific Nunc 96 Well Plate 2000 µL',
    squared: false,

    name: 'Thermo Scientific Nunc 96 Well Plate 2000 µL',
    max_volume: '2000 μL',
    well_count: 96,
    well_shape: 'U-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 16,
    label: 'USA Scientific 96 Deep Well Plate 2.4 mL',
    value: 'USA Scientific 96 Deep Well Plate 2.4 mL',
    squared: false,

    name: 'USA Scientific 96 Deep Well Plate 2.4 mL',
    max_volume: '2.4 mL',
    well_count: 96,
    well_shape: 'U-bottom',
    rows: 8,
    cols: 12,
  },
]

export const aluminium_blocks = [
  {
    id: 0,
    label: 'Select...',
    value: '',
    disabled: true,
    squared: false,

    name: '',
    max_volume: '',
    well_count: 0,
    well_shape: '',
    rows: 0,
    cols: 0,
  },
  {
    id: 1,
    label: 'Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap',
    value: 'Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap',
    max_volume: '2 ml',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 2,
    label: 'Opentrons 24 Well Aluminum Block with NEST 0.5 mL Screwcap',
    value: 'Opentrons 24 Well Aluminum Block with NEST 0.5 mL Screwcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with NEST 0.5 mL Screwcap',
    max_volume: '0.5 ml',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 3,
    label: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Screwcap',
    value: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Screwcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Screwcap',
    max_volume: '1.5 ml',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 4,
    label: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap',
    value: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap',
    max_volume: '1.5 ml',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 5,
    label: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Screwcap',
    value: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Screwcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Screwcap',
    max_volume: '2 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 6,
    label: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Snapcap',
    value: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Snapcap',
    squared: false,

    name: 'Opentrons 24 Well Aluminum Block with NEST 2 mL Snapcap',
    max_volume: '2 mL',
    well_count: 24,
    well_shape: 'U-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 7,
    label: 'Opentrons 96 Well Aluminum Block with Bio-Rad Well Plate 200 µL',
    value: 'Opentrons 96 Well Aluminum Block with Bio-Rad Well Plate 200 µL',
    squared: true,

    name: 'Opentrons 96 Well Aluminum Block with Bio-Rad Well Plate 200 µL',
    max_volume: '200 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,

  },
  {
    id: 8,
    label: 'Opentrons 96 Well Aluminum Block with Generic PCR Strip 200 µL',
    value: 'Opentrons 96 Well Aluminum Block with Generic PCR Strip 200 µL',
    squared: false,

    name: 'Opentrons 96 Well Aluminum Block with Generic PCR Strip 200 µL',
    max_volume: '200 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 9,
    label: 'Opentrons 96 Well Aluminum Block with NEST Well Plate 100 µL',
    value: 'Opentrons 96 Well Aluminum Block with NEST Well Plate 100 µL',
    squared: false,

    name: 'Opentrons 96 Well Aluminum Block with NEST Well Plate 100 µL',
    max_volume: '100 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 10,
    label: 'Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2 mL',
    value: 'Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2 mL',
    squared: true,

    name: 'Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2 mL',
    max_volume: '2 mL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 11,
    label: 'Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 µL Flat',
    value: 'Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 µL Flat',
    squared: false,

    name: 'Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 µL Flat',
    max_volume: '200 μL',
    well_count: 96,
    well_shape: 'Flat-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 12,
    label: 'Opentrons 96 PCR Adapter with Armadillo Well Plate 200 µl',
    value: 'Opentrons 96 PCR Adapter with Armadillo Well Plate 200 µl',
    squared: false,

    name: 'Opentrons 96 PCR Adapter with Armadillo Well Plate 200 µl',
    max_volume: '200 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 13,
    label: 'Opentrons 96 PCR Adapter with NEST Well Plate 100 µl',
    value: 'Opentrons 96 PCR Adapter with NEST Well Plate 100 µl',
    squared: false,

    name: 'Opentrons 96 PCR Adapter with NEST Well Plate 100 µl',
    max_volume: '100 μL',
    well_count: 96,
    well_shape: 'V-bottom',
    rows: 8,
    cols: 12,
  },
  {
    id: 14,
    label: 'Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µl Flat',
    value: 'Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µl Flat',
    squared: true,

    name: 'Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µl Flat',
    max_volume: '112 μL',
    well_count: 384,
    well_shape: 'Flat-bottom',
    rows: 16,
    cols: 24,
  },
]

export const tube_racks = [
  {
    id: 0,
    label: 'Select...',
    value: '',
    disabled: true,

    name: '',
    max_volume: '',
    well_count: 0,
    well_shape: '',
    rows: 0,
    cols: 0,
  },
  {
    id: 1,
    label: 'Opentrons 10 Tube Rack with Falcon 4x50 mL, 6x15 mL Conical',
    value: 'Opentrons 10 Tube Rack with Falcon 4x50 mL, 6x15 mL Conical',

    name: 'Opentrons 10 Tube Rack with Falcon 4x50 mL, 6x15 mL Conical',
    max_volume: '4x50 mL & 6x15 mL Conical',
    well_count: 10,
    well_shape: 'V-bottom',
    rows: 3,
    cols: 2,
    rows2: 2,
    cols2: 2,
  },
  {
    id: 2,
    label: 'Opentrons 10 Tube Rack with NEST 4x50 mL, 6x15 mL Conical',
    value: 'Opentrons 10 Tube Rack with NEST 4x50 mL, 6x15 mL Conical',

    name: 'Opentrons 10 Tube Rack with NEST 4x50 mL, 6x15 mL Conical',
    max_volume: '4x50 mL & 6x15 mL Conical',
    well_count: 10,
    well_shape: 'V-bottom',
    rows: 3,
    cols: 2,
  },
  {
    id: 3,
    label: 'Opentrons 15 Tube Rack with Falcon 15 mL Conical',
    value: 'Opentrons 15 Tube Rack with Falcon 15 mL Conical',

    name: 'Opentrons 15 Tube Rack with Falcon 15 mL Conical',
    max_volume: '15 mL',
    well_count: 15,
    well_shape: 'V-bottom',
    rows: 3,
    cols: 5,
  },
  {
    id: 4,
    label: 'Opentrons 15 Tube Rack with NEST 15 mL Conical',
    value: 'Opentrons 15 Tube Rack with NEST 15 mL Conical',

    name: 'Opentrons 15 Tube Rack with NEST 15 mL Conical',
    max_volume: '15 mL',
    well_count: 15,
    well_shape: 'V-bottom',
    rows: 3,
    cols: 5,
  },
  {
    id: 5,
    label: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',
    value: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',

    name: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',
    max_volume: '1.5 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 6,
    label: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',
    value: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',

    name: 'Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap',
    max_volume: '1.5 mL',
    well_count: 24,
    well_shape: 'U-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 7,
    label: 'Opentrons 24 Tube Rack with Generic 2 mL Screwcap',
    value: 'Opentrons 24 Tube Rack with Generic 2 mL Screwcap',

    name: 'Opentrons 24 Tube Rack with Generic 2 mL Screwcap',
    max_volume: '2 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 8,
    label: 'Opentrons 24 Tube Rack with NEST 0.5 mL Screwcap',
    value: 'Opentrons 24 Tube Rack with NEST 0.5 mL Screwcap',

    name: 'Opentrons 24 Tube Rack with NEST 0.5 mL Screwcap',
    max_volume: '0.5 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 9,
    label: 'Opentrons 24 Tube Rack with NEST 1.5 mL Screwcap',
    value: 'Opentrons 24 Tube Rack with NEST 1.5 mL Screwcap',

    name: 'Opentrons 24 Tube Rack with NEST 1.5 mL Screwcap',
    max_volume: '1.5 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 10,
    label: 'Opentrons 24 Tube Rack with NEST 1.5 mL Snapcap',
    value: 'Opentrons 24 Tube Rack with NEST 1.5 mL Snapcap',

    name: 'Opentrons 24 Tube Rack with NEST 1.5 mL Snapcap',
    max_volume: '1.5 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 11,
    label: 'Opentrons 24 Tube Rack with NEST 2 mL Screwcap',
    value: 'Opentrons 24 Tube Rack with NEST 2 mL Screwcap',

    name: 'Opentrons 24 Tube Rack with NEST 2 mL Screwcap',
    max_volume: '2 mL',
    well_count: 24,
    well_shape: 'V-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 12,
    label: 'Opentrons 24 Tube Rack with NEST 2 mL Snapcap',
    value: 'Opentrons 24 Tube Rack with NEST 2 mL Snapcap',

    name: 'Opentrons 24 Tube Rack with NEST 2 mL Snapcap',
    max_volume: '2 mL',
    well_count: 24,
    well_shape: 'U-bottom',
    rows: 4,
    cols: 6,
  },
  {
    id: 13,
    label: 'Opentrons 6 Tube Rack with Falcon 50 mL Conical',
    value: 'Opentrons 6 Tube Rack with Falcon 50 mL Conical',

    name: 'Opentrons 6 Tube Rack with Falcon 50 mL Conical',
    max_volume: '50 mL',
    well_count: 6,
    well_shape: 'V-bottom',
    rows: 2,
    cols: 3,
  },
  {
    id: 14,
    label: 'Opentrons 6 Tube Rack with NEST 50 mL Conical',
    value: 'Opentrons 6 Tube Rack with NEST 50 mL Conical',

    name: 'Opentrons 6 Tube Rack with NEST 50 mL Conical',
    max_volume: '50 mL',
    well_count: 6,
    well_shape: 'V-bottom',
    rows: 2,
    cols: 3,
  },

]



